<?php

namespace Yu\BobToWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogsFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogsFileRepository extends EntityRepository
{
}
