yu_bob_to_web_homepage:
    path:     /bobtoweb
    defaults: { _controller: YuBobToWebBundle:Default:index }
yu_bob_to_web_ajax_getlasts:
    path:     /bobtoweb/ajax/getlastslogs/{amount}
    defaults: { _controller: YuBobToWebBundle:Ajax:getLastLogs }
    requirements:
        amount: \d+