services:
#    yu_bob_to_web.example:
#        class: Yu\BobToWebBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    yu_bob_to_web.logger:
        class: Yu\BobToWebBundle\Logger\YuLogger
        arguments: [@service_container]
    yu_bob_to_web.playersManager:
        class: Yu\BobToWebBundle\Player\PlayersManager
        arguments: [@doctrine]
    yu_bob_to_web.serversManager:
        class: Yu\BobToWebBundle\Server\ServersManager
        arguments: [@service_container]
