services:
#    yu_bob_to_web.example:
#        class: Yu\BobToWebBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    yu_bob_to_web.logger:
        class: Yu\BobToWebBundle\Logger\YuLogger
        arguments: [@doctrine]
